# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ogcode < Formula
  desc "Agentic coding assistant with web UI"
  homepage "https://github.com/prasenjeet-symon/ogcode"
  version "0.22.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.22.1/ogcode_0.22.1_darwin_x86_64.tar.gz"
      sha256 "303b945d1aae6dd7843173f89bb85334b719d9cd741d4dc841ed2d2273f10b59"

      define_method(:install) do
        bin.install "ogcode"
        (share/"ogcode/search-bridge").mkpath
        (share/"ogcode/search-bridge").install "search-bridge/server.js"
        (share/"ogcode/search-bridge").install "search-bridge/package.json"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.22.1/ogcode_0.22.1_darwin_arm64.tar.gz"
      sha256 "ee0dbf7a465d8c2e15329bcb8c3d9b035c2daffa7881cff19207326bdbf21a24"

      define_method(:install) do
        bin.install "ogcode"
        (share/"ogcode/search-bridge").mkpath
        (share/"ogcode/search-bridge").install "search-bridge/server.js"
        (share/"ogcode/search-bridge").install "search-bridge/package.json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.22.1/ogcode_0.22.1_linux_x86_64.tar.gz"
      sha256 "95a3f14ffbb7f94d32cf1ae4e1e99abf0af78a2e78dcae6b07cf35a63a26f623"
      define_method(:install) do
        bin.install "ogcode"
        (share/"ogcode/search-bridge").mkpath
        (share/"ogcode/search-bridge").install "search-bridge/server.js"
        (share/"ogcode/search-bridge").install "search-bridge/package.json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.22.1/ogcode_0.22.1_linux_arm64.tar.gz"
      sha256 "02e23dc814392a33b8e30737309a5cf17fdfb58fd9214b6ac3c3b68e79744026"
      define_method(:install) do
        bin.install "ogcode"
        (share/"ogcode/search-bridge").mkpath
        (share/"ogcode/search-bridge").install "search-bridge/server.js"
        (share/"ogcode/search-bridge").install "search-bridge/package.json"
      end
    end
  end

  def post_install
    bridge_dir = share/"ogcode/search-bridge"
    if which("node") && which("npm")
      system "npm", "install", "--legacy-peer-deps", "--prefix", bridge_dir.to_s, "--silent"
      system "npx", "playwright", "install", "chromium"
      ohai "Web search agent ready. Enable it in ogcode Settings → General."
    end
  end

  def caveats
    <<~EOS
      ogcode installed! Run `ogcode --help` to get started.

      Web Search Agent (optional):
        Requires Node.js. To enable after install:
          cd #{HOMEBREW_PREFIX}/share/ogcode/search-bridge
          npm install
          npx playwright install chromium
        Then enable search in ogcode Settings → General.
    EOS
  end

  test do
    system "#{bin}/ogcode", "--help"
  end
end
