# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ogcode < Formula
  desc "Agentic coding assistant with web UI"
  homepage "https://github.com/prasenjeet-symon/ogcode"
  version "0.13.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.13.3/ogcode_0.13.3_darwin_x86_64.tar.gz"
      sha256 "071ddf4201bebc445503f86a775c9f018e608b72e4f72f6b662ecc2420e4ef24"

      define_method(:install) do
        bin.install "ogcode"
        (share/"ogcode/search-bridge").mkpath
        (share/"ogcode/search-bridge").install "search-bridge/server.js"
        (share/"ogcode/search-bridge").install "search-bridge/package.json"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.13.3/ogcode_0.13.3_darwin_arm64.tar.gz"
      sha256 "8bbe7156971f09107126ca66b01db33cff6e7cc72846f057d057c0270ed64109"

      define_method(:install) do
        bin.install "ogcode"
        (share/"ogcode/search-bridge").mkpath
        (share/"ogcode/search-bridge").install "search-bridge/server.js"
        (share/"ogcode/search-bridge").install "search-bridge/package.json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.13.3/ogcode_0.13.3_linux_x86_64.tar.gz"
      sha256 "0ca48a40af2bd3a942ca912b6909cfdb427ec866d149a98001345b7e4b1f8f82"
      define_method(:install) do
        bin.install "ogcode"
        (share/"ogcode/search-bridge").mkpath
        (share/"ogcode/search-bridge").install "search-bridge/server.js"
        (share/"ogcode/search-bridge").install "search-bridge/package.json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.13.3/ogcode_0.13.3_linux_arm64.tar.gz"
      sha256 "bbfe37cd269b1e39ff4f8c86ce4ff61a5da4c5636baf00bb7f299f50937927a2"
      define_method(:install) do
        bin.install "ogcode"
        (share/"ogcode/search-bridge").mkpath
        (share/"ogcode/search-bridge").install "search-bridge/server.js"
        (share/"ogcode/search-bridge").install "search-bridge/package.json"
      end
    end
  end

  def post_install
    bridge_dir = share/"ogcode/search-bridge"
    if which("node") && which("npm")
      system "npm", "install", "--legacy-peer-deps", "--prefix", bridge_dir.to_s, "--silent"
      system "npx", "playwright", "install", "chromium"
      ohai "Web search agent ready. Enable it in ogcode Settings → General."
    end
  end

  def caveats
    <<~EOS
      ogcode installed! Run `ogcode --help` to get started.

      Web Search Agent (optional):
        Requires Node.js. To enable after install:
          cd #{HOMEBREW_PREFIX}/share/ogcode/search-bridge
          npm install
          npx playwright install chromium
        Then enable search in ogcode Settings → General.
    EOS
  end

  test do
    system "#{bin}/ogcode", "--help"
  end
end
