# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ogcode < Formula
  desc "Agentic coding assistant with web UI"
  homepage "https://github.com/prasenjeet-symon/ogcode"
  version "0.44.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.44.0/ogcode_0.44.0_darwin_x86_64.tar.gz"
      sha256 "03b6daf7694122735c91aa43b5c07e6b437b9f90062a5925caae9623fb5b7919"

      define_method(:install) do
        bin.install "ogcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.44.0/ogcode_0.44.0_darwin_arm64.tar.gz"
      sha256 "b4fe8608507c2f2cade05392e3df31cb4d30be4f0d587b2d05131abd6f76e15b"

      define_method(:install) do
        bin.install "ogcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.44.0/ogcode_0.44.0_linux_x86_64.tar.gz"
      sha256 "9831b808c67aa2aaa16864eb0e7bf1a17ddce6a3a44d5333ec7a670cccc9e5cf"
      define_method(:install) do
        bin.install "ogcode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prasenjeet-symon/ogcode/releases/download/v0.44.0/ogcode_0.44.0_linux_arm64.tar.gz"
      sha256 "9d07bcd9b7b6503e5f3a281e16d63da11d07be3e145dd1ee2385a8f5d06d9d55"
      define_method(:install) do
        bin.install "ogcode"
      end
    end
  end

  def caveats
    <<~EOS
      ogcode installed! Run `ogcode --help` to get started.

      Web search is built in and enabled by default — nothing else to install.
    EOS
  end

  test do
    system "#{bin}/ogcode", "--help"
  end
end
